services:
  db:
    image: postgres:18
    container_name: rubedo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: rubedo
      POSTGRES_PASSWORD: rubedo
      POSTGRES_DB: rubedo_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
