default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: rubedo
  password: rubedo
  port: 5434

cache: &cache
  <<: *default
  migrations_paths: db/cache_migrate
queue: &queue
  <<: *default
  migrations_paths: db/queue_migrate
cable: &cable
  <<: *default
  migrations_paths: db/cable_migrate

development:
  primary:
    <<: *default
    database: rubedo_development
    min_messages: log
  cache:
    <<: *cache
    database: rubedo_development_cache
  queue:
    <<: *queue
    database: rubedo_development_queue
  cable:
    <<: *cable
    database: rubedo_development_cable

test:
  <<: *default
  database: rubedo_test
  # primary:
  #   <<: *default
  #   database: rubedo_test
  # cache:
  #   <<: *cache
  #   database: rubedo_test_cache
  # queue:
  #   <<: *queue
  #   database: rubedo_test_queue
  # cable:
  #   <<: *cable
  #   database: rubedo_test_cable

production:
  primary: &primary_production
    <<: *default
    database: rubedo_production
    username: rubedo
    password: <%= ENV["RUBEDO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rubedo_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rubedo_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rubedo_production_cable
    migrations_paths: db/cable_migrate
