default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: rubedo_development
  username: <%= ENV.fetch("DB_USERNAME", "rubedo") %>
  password: <%= ENV.fetch("DB_PASSWORD", "rubedo") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

test:
  <<: *default
  database: rubedo_test
  username: <%= ENV.fetch("DB_USERNAME", "rubedo") %>
  password: <%= ENV.fetch("DB_PASSWORD", "rubedo") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

production:
  <<: *default
  database: rubedo_production
  username: <%= Rails.application.credentials.dig(:db, :username) %>
  password: <%= Rails.application.credentials.dig(:db, :password) %>
  host: <%= Rails.application.credentials.dig(:db, :host) %>
